### ISSUE TITLE
Inputs não-controlados e controlados

### ISSUE THREAD

**Issue by jvzaniolo** [RafaelAndeloci/ToDoApp#3]
Pesquise sobre a diferença entre inputs controlados e não controlados em React, e migre a implementação do input do `<TaskForm>` para usar inputs não controlados.

**Comment by RafaelAndeloci** [comment]
Alterei lá. O que eu entendi a respeito de **Controlled Inputs** e **Uncontrolled Inputs** é: 

- **Controlled Inputs** é quando inputs são controllados utilizando o `useState()`, fazendo com que o componente atualize ao ser modificado pelo usuário. Logo quando o usuário mudar por exemplo uma letra dentro de um input text que utilize essa abordagem o componente irá ser renderizado dnv. Pelo que eu li, é melhor prática utilizar o Controlled Input do que o Uncontrolled e ele em geral é mais rápido. Outra coisa que li também é que Controlled Inputs têm seu estado e comportamento gerenciado pelos componentes pais do mesmo.

- **Uncontrolled Inputs** é quando inputs são controllados internamente no componente e os dados de um formulário não são gravados no seu estado interno, deixando o DOM interagir com os dados do input diretamente. Em geral Uncontrolled inputs funcionam de um jeito em que o estado do componente não muda com a interação do usuário.

**Comment by RafaelAndeloci** [comment]
Foi isso que eu entendi pelo menos no geral :P

**Comment by jvzaniolo** [comment]
> é melhor prática utilizar o Controlled Input do que o Uncontrolled e ele em geral é mais rápido.

Você pode mandar o link do material que você leu sobre isso?

> Em geral Uncontrolled inputs funcionam de um jeito em que o estado do componente não muda com a interação do usuário.

Na verdade o estado muda sim, tanto que é possível ter acesso ao valor que o usuário colocou no input usando JavaScript. 
A questão é que quem gerencia esse estado é o próprio input, ao invés de manualmente controlar o valor dele com `useState`.

**Comment by jvzaniolo** [comment]
Tenta chegar em uma implementação sem usar a `ref` do input?
Dica: `new FormData()`

https://github.com/RafaelAndeloci/ToDoApp/blob/173611d5be0fb8f556aed95510ce0fa90d3ffbaf/src/components/TaskForm.jsx#L13

**Comment by jvzaniolo** [comment]
Vou fechar a issue por conta da discussão que tivemos na aula passada.
